dashboard/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Home, name='DashboardHome'),
    path('MyServices', views.MyServices, name='MyServices'),
    path('AddService', views.AddService, name='AddService'),

    path('UserServiceCreationProgress/<int:id>', views.UserServiceCreationProgress, name='UserServiceCreationProgress'),
    path('ResetPasswordService/<int:id>', views.ResetPasswordService, name='ResetPasswordService'),
    
    path('ServicePlans/<int:id>', views.ServicePlans, name='ServicePlans'),
    path('ViewService/<int:id>', views.ViewService, name='ViewService'),
    
    path('buliding_waiting_page/<int:user_service_id>', views.buliding_waiting_page, name='buliding_waiting_page'),
    path('check_is_deployed/<int:user_service_id>', views.check_is_deployed, name='check_is_deployed'),
]

pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('Services/PatientManagement', views.PatientManagement, name='PatientManagement'),
    path('Services/SchoolManagement', views.SchoolManagement, name='SchoolManagement'),
    path('Services/HRManagement', views.HRManagement, name='HRManagement'),
    path('SubscribeToUs', views.SubscribeToUs, name='SubscribeToUs'),
    path('Contact', views.Contact, name='Contact'),
    path('change_language/', views.change_language, name='change_language'),

]

dashboard/models.py
from django.db import models
from django.contrib.auth.models import User
import random, string, datetime
from django.utils.translation import gettext_lazy as _ 
# Create your models here.


def payOrderSecretCodeGen():
    N = 99
    res = ''.join(random.choices((string.digits+string.ascii_letters), k=N))
    return str(res)

services_choices = [
    ('1', _('Patient Management')),
    ('2', _('School Management')),
    ('3', _('HR Management')),
]

plan_scope_choices = [
    ('1', _('Monthly')),
    ('2', _('Yearly'))
]

order_progress_choices = [
    ('1', _('Pending')),
    ('2', _('Paid')),
    ('3', _('Complited')),
    ('4', _('Cancelled'))
]

user_service_progress_choices = [
    ('1', _('Create Project')),
    ('2', _('Choose Plan')),
    ('3', _('Project Settings')),
    ('4', _('Complited'),
)]

system_progress_choices = [
    ('1', _('Pending')),
    ('2', _('Building')),
    ('3', _('Complited')),
    ('4', _('Failed'),
)]

class ServicesModel(models.Model):
    title = models.CharField(max_length=254, verbose_name=_("Service Title"))
    sub_title = models.TextField(verbose_name=_("Subtitle"))
    service = models.CharField(max_length=254, choices=services_choices, verbose_name=_("Service"))

    creation_datetime = models.DateTimeField(auto_now_add=True, verbose_name=_("Creation Date"))

    class Meta:
        verbose_name = _("Service Model")
        verbose_name_plural = _("Service Models")

    def __str__(self):
        return str(self.get_service_display())


class UserServiceModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, verbose_name=_("User"))
    project_name = models.CharField(max_length=254, null=True, verbose_name=_("Project Name"))
    service = models.ForeignKey(ServicesModel, on_delete=models.CASCADE, null=True, verbose_name=_("Service"))
    progress = models.CharField(max_length=254, choices=user_service_progress_choices, null=True, verbose_name=_("Progress"))

    service_subscription_id = models.CharField(max_length=254, null=True, verbose_name=_("Service Subscription ID"))
    service_user_id = models.CharField(max_length=254, null=True, verbose_name=_("Service User ID"))
    service_subscription_date = models.CharField(max_length=254, null=True, verbose_name=_("Service Subscription Date"))
    plan_scope = models.CharField(max_length=254, choices=plan_scope_choices, null=True, verbose_name=_("Plan Scope"))
    
    system_port = models.CharField(max_length=254, null=True, blank=True, verbose_name=_("system_port"), unique=True)
    subdomain = models.CharField(max_length=254, null=True, blank=True, verbose_name=_("Subdomain"))
    system_progress = models.CharField(max_length=254, default='1', choices=system_progress_choices, null=True, verbose_name=_("System Progress"))

    creation_datetime = models.DateTimeField(auto_now_add=True, verbose_name=_("Creation Date"))

    class Meta:
        verbose_name = _("User Service Model")
        verbose_name_plural = _("User Service Models")

    def __str__(self):
        return str(self.project_name)

    @property
    def get_avarible_port(self):
        """
        دالة لتوليد منفذ فريد غير مستخدم.
        """
        # البحث عن المنافذ المحجوزة
        reserved_ports = UserServiceModel.objects.exclude(system_port__isnull=True).values_list('system_port', flat=True)

        # البحث عن منفذ متاح
        for port in range(9000, 65535):
            port = str(port)
            if port not in reserved_ports:
                # إذا كان المنفذ غير محجوز، يتم إرجاعه
                return port

        # في حال لم يوجد منفذ متاح
        return None

    def get_unique_subdomain(self, subdomain):
        """
        دالة للتحقق مما إذا كان الـ subdomain موجودًا بالفعل في قاعدة البيانات.
        إذا كان موجودًا، سيتم إرجاع قيمة فريدة بتعديل الاسم.
        """
        subdomain = 'ppp' + subdomain.replace(" ", "")
        original_subdomain = subdomain
        counter = 1

        # التحقق من وجود الـ subdomain في قاعدة البيانات
        while UserServiceModel.objects.filter(subdomain=subdomain).exists():
            subdomain = f"{original_subdomain}{counter}"  # إضافة رقم لتمييز الـ subdomain
            counter += 1

        return subdomain

    @property
    def remaining_subscription(self):
        subscription_date = self.service_subscription_date
        if subscription_date:
            subscription_days = 30 if self.plan_scope else 365
            subscription_end_date = (datetime.timedelta(days=subscription_days) + subscription_date) - subscription_date



dashboard/forms.py
from django import forms
from .models import UserServiceModel
from .fields import CountrysChoices

class AddUserServiceModelForm(forms.ModelForm):

    class Meta:
        model = UserServiceModel
        fields = ['project_name', 'service']

        widgets = {
            'project_name': forms.TextInput(attrs={'class':'form-control', 'placeholder':'New Project Name'}),
            'service': forms.Select(attrs={'class':'form-select', 'placeholder':'Choose Service'}),
        }

PatientManagementLANGUAGES = [
    ('ar', 'العربية'),
    ('en', 'English'),
    ('de', 'Deutsch'),
    ('he', 'עִברִית'),
    ('ro', 'Românește'),
    
]

SchoolManagementLANGUAGES = [
    ('ar', 'العربية'),
    ('en', 'English'),
    ('de', 'Deutsch'),
    ('he', 'עִברִית'),
    ('ro', 'Românește'),
    
]


class PatientManagementHospital(forms.Form):
    first_name = forms.CharField(max_length=254, widget=forms.TextInput({'class':'form-control'}))
    last_name = forms.CharField(max_length=254, widget=forms.TextInput({'class':'form-control'}))
    username = forms.CharField(max_length=254, widget=forms.TextInput({'class':'form-control'}))
    password = forms.CharField(label='password', max_length=254, widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Password'}))
    name = forms.CharField(max_length=254, widget=forms.TextInput({'class':'form-control'}))
    number = forms.CharField(max_length=254, widget=forms.TextInput({'class':'form-control'}))
    address = forms.CharField(max_length=254, widget=forms.TextInput({'class':'form-control'}))
    lang = forms.ChoiceField(choices=PatientManagementLANGUAGES, widget=forms.Select({'class':'form-select'}))

class SchoolManagementProfile(forms.Form):
    first_name = forms.CharField(max_length=254, widget=forms.TextInput({'class':'form-control'}))
    last_name = forms.CharField(max_length=254, widget=forms.TextInput({'class':'form-control'}))
    username = forms.CharField(max_length=254, widget=forms.TextInput({'class':'form-control'}))
    password = forms.CharField(label='password', max_length=254, widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Password'}))
    name = forms.CharField(max_length=254, widget=forms.TextInput({'class':'form-control'}))
    number = forms.CharField(max_length=254, widget=forms.TextInput({'class':'form-control'}))
    address = forms.CharField(max_length=254, widget=forms.TextInput({'class':'form-control'}))
    academic_year = forms.IntegerField(widget=forms.NumberInput({'class':'form-control', "min":"0", "placeholder":"2025"}))
    lang = forms.ChoiceField(choices=SchoolManagementLANGUAGES, widget=forms.Select({'class':'form-select'}))
    country = forms.ChoiceField(choices=CountrysChoices, widget=forms.Select({'class':'form-select'}))

class HRManagementProfile(forms.Form):
    first_name = forms.CharField(max_length=254, widget=forms.TextInput({'class':'form-control'}))
    last_name = forms.CharField(max_length=254, widget=forms.TextInput({'class':'form-control'}))
    username = forms.CharField(max_length=254, widget=forms.TextInput({'class':'form-control'}))
    email = forms.EmailField(widget=forms.TextInput({'class':'form-control'}))
    password = forms.CharField(label='password', max_length=254, widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Password'}))
    number = forms.CharField(max_length=254, widget=forms.TextInput({'class':'form-control'}))

dashboard/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.urls import reverse
from .forms import (AddUserServiceModelForm, PatientManagementHospital, SchoolManagementProfile, HRManagementProfile)
from .models import (ServicesModel, UserServiceModel)
from django.contrib import messages
from django.conf import settings
import json, requests
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from decimal import Decimal
from .tools import data_base, deploy
from .projects_setting import hr_setting
import os
from billing.models import ServicePaymentOrderModel
from deployments.models import Deployment
# Create your views here.
PAYPAL_RECIVVER_EMAIL = settings.PAYPAL_RECIVVER_EMAIL



def Home(request):
    user = request.user
    user_services = Deployment.objects.filter(user=user)
    orders = ServicePaymentOrderModel.objects.filter(user=user)
    active_user_services = user_services.filter(status=2)
    copmlited_orders = orders.filter(progress='3')
    uncopmlited_orders = orders.exclude(progress='3')
    
    context = {
        'active_user_services': active_user_services.count(),
        'copmlited_orders': copmlited_orders.count(),
        'uncopmlited_orders': uncopmlited_orders.count(),
        'orders':orders
    }
    return render(request, 'dashboard/home.html', context)

def MyServices(request):
    user_services = UserServiceModel.objects.filter(user=request.user).order_by('-id')
    return render(request, 'dashboard/services/MyServices.html', {'user_services':user_services})




def ResetPasswordService(request, id):
    if request.method == 'POST':
        password = request.POST.get('password')
        password2 = request.POST.get('password2')
        if password == password2:
            data = {
                'password':password
            }
            res_data = {}
            user_services = UserServiceModel.objects.get(id=id)
            service_user_id = user_services.service_user_id
            selected_service = user_services.service.service


            if service_user_id:
                if selected_service == '1':
                    res = requests.post(f'{PatientManagementURL}/en/accounts/ResetPasswordAPI/{service_user_id}', data=data)
                elif selected_service == '2':
                    res = requests.post(f'{SchoolManagementURL}/en/ResetPasswordAPI/{service_user_id}', data=data)
                elif selected_service == '3':
                    response_data, exit_code = hr_docker.change_user_password(user_services.subdomain, service_user_id, password)
                    if exit_code == 0:
                        res_data['status'] = True
                    else:
                        res_data['status'] = False

                if not res_data:
                    if res.status_code == 200:
                        res_data = res.json()
                    else:messages.error(request, 'error on trying connect to server please call support')

                if res_data.get('status'):
                    messages.success(request, 'Password has been changed successfully')
                else:
                    messages.error(request, 'Password not changed got some errors, please call support')
            else:messages.error(request, 'error on changing password please call support')
        else:messages.error(request, 'new password field and repeat new password field not same')
    return redirect('ViewService', id)


def check_is_deployed(request, user_service_id):
    user_service = UserServiceModel.objects.get(id=user_service_id)
    # r = hr_docker.check_migrations(user_service.subdomain)
    url = f'http://77.37.122.10:{user_service.system_port}/'
    r = False
    try:
        res = requests.get(url, timeout=4)
        if res.status_code == 200 or res.status_code == 301 or res.status_code == 302:
            r = True
    except:
        pass
    return JsonResponse({'success':r}, safe=False)

def buliding_waiting_page(request, user_service_id):
    check_is_deployed_url = reverse('check_is_deployed', kwargs={'user_service_id':user_service_id})
    success_page = reverse('AddHRManagementSettings', kwargs={'id':user_service_id})
    return render(request, 'dashboard/bulding/buliding_waiting_page.html', {'check_is_deployed_url':check_is_deployed_url, 'success_page':success_page})

def DeploySystem(request, user_service):
    if user_service.system_progress == '3':
        return redirect('buliding_waiting_page', user_service.id)

    project_name = 'horilla'
    domain = 'softmsg.com'
    subdomain = user_service.subdomain if user_service.subdomain else user_service.get_unique_subdomain(user_service.project_name)
    port = user_service.system_port if user_service.system_port else user_service.get_avarible_port
    user_service.subdomain = subdomain
    user_service.system_port = port
    static_folder_name = 'staticfiles'

    #create database for project
    # creating_database = data_base.create_database(db_name=subdomain, user=DEFAULT_HR_DB_USER, password=DEFAULT_HR_DB_PASS, host='77.37.122.10', port='5434')
    print('adding service')
    hr_docker.add_hr_service(subdomain, port)
    print('runing container')
    hr_docker.compose_up(subdomain)
    # hr_docker.run_container(subdomain, port)
    print('success')
    
    if os.name == "posix":
        #create nginx for app
        deploying = deploy.create_nginx_config(static_folder_name, subdomain, port, domain)
        deploy.restart_services()
    # if creating_database:
    user_service.system_progress = '3'
    user_service.save()
    return redirect('buliding_waiting_page', user_service.id)
    # else:
    #     user_service.system_progress = '4'
    #     user_service.save()
    #     messages.error(request, 'حدث خطاء اثناء بناء النظام')
    #     return redirect('MyServices')
    
    
    

def UserServiceCreationProgress(request, id):
    user_service = UserServiceModel.objects.get(id=id)
    progress = user_service.progress
    if progress == '1': return redirect('AddService')
    elif progress == '2': return redirect('ServicePlans', id)
    elif progress == '3':
        if user_service.service.service == '1':
            return redirect('AddPatientManagementSettings', id)
        elif user_service.service.service == '2':
            return redirect('AddSchoolManagementSettings', id)
        elif user_service.service.service == '3':
            return DeployHRSystem(request, user_service)
    elif progress == '4':
        return redirect('ViewService', id)
    return redirect('MyServices')

def AddService(request):
    service_info_url = reverse('GetServiceInfo')
    form = AddUserServiceModelForm()
    if request.method == 'POST':
        form = AddUserServiceModelForm(data=request.POST)
        if form.is_valid():
            user_service = form.save(commit=False)
            user_service.user = request.user
            user_service.progress = '2'
            user_service.save()

            return redirect('UserServiceCreationProgress', user_service.id)
    return render(request, 'dashboard/services/AddService.html', {'form':form, 'service_info_url':service_info_url})


def ServicePlans(request, id):
    user_service = UserServiceModel.objects.get(id=id)

    return render(request, 'dashboard/services/ServicePlans.html', {'user_service':user_service})




def ViewService(request, id):
    
    return





templates/dashboard/services/AddService.html
{% extends "dashboard_base.html" %}
{% load i18n %}
{% block sheri %}
<div class="bg-light-orange p-3">
    <a href="{% url 'AddService' %}" class="btn btn-light">{% trans "Add Service" %}</a>
</div>




<!-- Project Form -->
<div class="container p-4 ">
    <h5>{% trans "Create Project" %}</h5>

    <form class="bg-body-tertiary p-4 rounded needs-validation" novalidate id="project_form" method="post">
        {% csrf_token %}
        <div class="row row-cols-1 row-cols-md-2">
            <div class="mb-3 col">
                <label for="exampleFormControlInput1" class="form-label">
                    <i class="bi bi-pen"></i>
                    {% trans "Project Name" %}
                </label>
                {{form.project_name}}
                <div class="valid-feedback">
                    {% trans "Looks good!" %}
                  </div>
                  <div class="invalid-feedback">
                    {% trans "Please fill a project name." %}
                  </div>
            </div>
            <div class="mb-3 col">
                <label for="exampleFormControlInput1" class="form-label">
                    <i class="bi bi-hdd"></i>
                    {% trans "Service" %}
                </label>
                {{form.service}}
                <div class="valid-feedback">
                    {% trans "Looks good!" %}
                </div>
                <div class="invalid-feedback">
                    {% trans "Please select a service." %}
                </div>
            </div>
        </div>

        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">
                <i class="bi bi-card-list"></i>
                {% trans "Service Description" %}
            </label>
            <textarea class="form-control" id="ServiceDescription" name="" id="" rows="5" disabled></textarea>
        </div>

        <!-- Progress -->
        <div class="mb-3">
            <h5>{% trans "Progress" %}</h5>
            <div class="row row-cols-2 row-cols-md-4 justify-content-md-between g-4 text-center text-black">
                <div class="col">
                    <button type="button" class="btn btn-outline-dark px-3 rounded-4 active">
                        <i class="bi bi-1-square fs-5"></i>
                    </button>
                    <span class="fw-bold d-block">
                      <i class="bi bi-hourglass-split"></i>
                      {% trans "Create Project" %}</span>
                </div>
                <div class="col">
                    <button type="button" class="btn btn-outline-dark px-3 rounded-4">
                        <i class="bi bi-2-square fs-5"></i>
                    </button>
                    <span class="fw-bold d-block">
                      <i class="bi bi-patch-exclamation"></i>
                      {% trans "Choose Plan" %}</span>
                </div>
                <div class="col">
                    <button type="button" class="btn btn-outline-dark px-3 rounded-4">
                        <i class="bi bi-3-square fs-5"></i>
                    </button>
                    <span class="fw-bold d-block">
                      <i class="bi bi-patch-exclamation"></i>
                        {% trans "Project Settings" %}</span>
                </div>
                <div class="col">
                    <button type="button" class="btn btn-outline-dark px-3 rounded-4">
                        <i class="bi bi-4-square fs-5"></i>
                    </button>
                    <span class="fw-bold d-block">
                      <i class="bi bi-patch-exclamation"></i>
                        {% trans "Done" %}</span>
                </div>
            </div>
        </div>
        <!-- End Progress -->


        <button type="submit" class="btn bg-light-orange">{% trans "Next" %}
            <i class="bi bi-caret-right-fill"></i>
        </button>
    </form>
</div>
<!-- End Project Form -->
<div class="py-4"></div>


<script>
    const selectService = document.querySelector('#project_form select[name="service"]')
    selectService.addEventListener('change', GetServiceInfo)

    function GetServiceInfo() {
        let ServiceDescription = document.querySelector('#ServiceDescription')
        
        if (selectService.value) {
            fetchAsync(`{{service_info_url}}?id=${selectService.value}`).then(data => {
            if (data) {
                if (data.status) {
                    
                    ServiceDescription.innerHTML = data.subtitle
                }
            }
            })

        } else {
                ServiceDescription.innerHTML = ''
        }
    }
</script>
{% endblock %}

templates/dashboard/services/MyServices.html
{% extends "dashboard_base.html" %}
{% load i18n %}
{% block sheri %}
<div class="bg-light-orange p-3">
    <a href="{% url 'project_list' %}" class="btn btn-light">{% trans "Buy Service" %}</a>
</div>



<div class="container p-4 ">
    <h5>{% trans "My Service" %}</h5>
  <div class="tabel-box">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">{% trans "Project" %}</th>
          <th scope="col">{% trans "Service" %}</th>
          <th scope="col">{% trans "Status" %}</th>
          {% comment %} <th scope="col">Subscription</th> {% endcomment %}
          <th scope="col">{% trans "Options" %}</th>
        </tr>
      </thead>
      <tbody>

        {% for user_service in user_services %}
        <tr>
          <th scope="row">{{forloop.counter}}</th>
          <td>{{user_service.project_name}}</td>
          <td>{{user_service.service.get_service_display}}</td>
          <td><span class="bg-light-orange px-2 py-1 rounded text-nowrap">{{user_service.get_progress_display}}</span></td>
          {% comment %} <td>remaining 2 days, {{user_service.remaining_subscription}}</td> {% endcomment %}
          <td>
              <a href="{% url 'UserServiceCreationProgress' user_service.id %}" class="btn bg-light-orange my-1">
                  {% trans "View" %}
              </a>
              <a class="btn btn-danger my-1" data-bs-toggle="modal" onclick="deleteItem('{% url 'DeleteService' user_service.id %}')" data-bs-target="#exampleModal">{% trans "Delete" %}</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

</div>



<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content rounded-3 shadow">
      <div class="modal-body p-4 text-center">
        <h5 class="mb-0">{% trans "Delete this service?" %}</h5>
        <p class="mb-0">{% trans "after deleting this service you can't restore again." %}</p>
      </div>
      <div class="modal-footer flex-nowrap p-0">
        <a type="button" id="yesDelete" class="btn btn-lg btn-link fs-6 text-decoration-none col-6 py-3 m-0 rounded-0 border-end"><strong>{% trans "Yes, delete" %}</strong></a>
        <button type="button" class="btn btn-lg btn-link fs-6 text-decoration-none col-6 py-3 m-0 rounded-0" data-bs-dismiss="modal">{% trans "No thanks" %}</button>
      </div>
    </div>
  </div>
</div>
<!-- end Modal  -->

<script>
  function deleteItem(id){
    document.querySelector('#yesDelete').href = id
  }
</script>
{% endblock sheri %}